### ISSUE TITLE
vue-query/fetch runs res.json on DELETE with NoContent

### ISSUE THREAD

**Issue by davidysoards** [orval-labs/orval#1545] opened 2024-07-28 04:37 UTC
## What are the steps to reproduce this issue?

1. using this spec: https://github.com/dys-org/mono/blob/orval-fetch-query-bugs/go/oapi-todo/api/openapi.yaml
with orval config:
```
output: {
  client: 'vue-query',
  httpClient: 'fetch',
},
```
2. run `orval generate`

This file is generated: https://github.com/dys-org/mono/blob/orval-fetch-query-bugs/js/packages/oapi-todo/src/api.ts

## What happens?

Firing the `deleteTodosId` method results in an error
```
SyntaxError: Unexpected end of JSON input
    at deleteTodosId (api.ts:360:26)
```
because it runs `res.json()` on a payload with no body.

## What were you expecting to happen?

The function generated for this  DELETE endpoint with 204 No Content response should not expect a JSON body or try to return data.
```
delete:
  summary: Delete a todo by ID
  parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
  responses:
    "204":
      description: No Content
```

```diff
export const deleteTodosId = async (
  id: number,
  options?: RequestInit,
): Promise<deleteTodosIdResponse> => {
  const res = await fetch(getDeleteTodosIdUrl(id), {
    ...options,
    method: 'DELETE',
  });
-  const data = await res.json();

-  return { status: res.status, data };
+  return { status: res.status };
};
```

Which also means the generated response type should not have `data`:
```diff
export type deleteTodosIdResponse = {
- data: void;
  status: number;
};
```

## What versions are you using? 

**Operating System:** Mac OS
**Package Version:** 7.0.0
**Browser Version:** Brave

**Comment by davidysoards** [comment] 2024-08-07 00:50
wdyt @soartec-lab ? this can probably be solved with custom fetch but default should respect response defined in the spec.

**Comment by soartec-lab** [comment] 2024-08-08 00:18
Hi, @davidysoards 
Hmm, I don't think I can do it. This is because the response type requires a generated type.
Would you like to try this option? This might solve your problem.

**Comment by douweknook** [comment] 2024-08-08 12:15
I am running into the same problem using only the `fetch` client. I have this openapi spec:
```
/templates/{id}:
    delete:
      description: Delete a template by ID
      operationId: deleteTemplate
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: No Content
```

Which results in this api code:
```
/**
 * Delete a template by ID
 */
export type deleteTemplateResponse = {
  data: void
  status: number
}

export const getDeleteTemplateUrl = (id: string) => {
  return `https://localhost:3000/templates/${id}`
}

export const deleteTemplate = async (
  id: string,
  options?: RequestInit,
): Promise<deleteTemplateResponse> => {
  const res = await fetch(getDeleteTemplateUrl(id), {
    ...options,
    method: 'DELETE',
  })
  const data = await res.json()

  return { status: res.status, data }
}
```

This blows up whenever I try to make this request as the response is empty. The issue is in the line `const data = await res.json()`. It throws `ERROR SyntaxError: Unexpected end of JSON input` because it cannot parse the response data as there is none.

As far as I can tell my spec is correct and I am unable to find a way to add a transformer or override into my config to get rid of this. Is this a bug? And is there any workaround available for this?

**Comment by soartec-lab** [comment] 2024-08-09 00:03
Thanks. I understand now.
you said that is correct. Currently the `fetch` client only supporting just basic case.
Therefore, you need to create a custom fetch function to handle the response.

below is an example of a custom fetch function that you can avoid error due to empty response.

```ts
const getBody = async <T>(c: Response | Request): Promise<T> => {
	const text = await c.text();

	if (!text) {
		return {} as T;
	}

        const contentType = c.headers.get("content-type");

	if (contentType?.includes("application/json")) {
		return JSON.parse(text);
	}

	return text as unknown as T;
};

export const customFetch = async <T>(
	url: string,
	options: RequestInit,
): Promise<T> => {
	const requestInit: RequestInit = {
		...options,
	};

	const request = new Request(url, requestInit);
	const response = await fetch(request);
	const data = await getBody<T>(response);

	return { status: response.status, data } as T;
};
```

And you can check all sample code.

https://github.com/orval-labs/orval/blob/master/samples/next-app-with-fetch/custom-fetch.ts

orval config:

https://github.com/orval-labs/orval/blob/master/samples/next-app-with-fetch/orval.config.ts

Give it a try.

**Comment by douweknook** [comment] 2024-08-09 07:27
Aaah, this is super helpful. Thanks!

**Comment by soartec-lab** [comment] 2024-08-11 01:49
I added a `workaround` label to this issue. If you want to avoid errors in `res.json()`, you can do that with a custom fetch so close this.

**Closed by soartec-lab** 2024-08-11 01:49 UTC
Labels: workaround, tanstack-query, fetch
